print("***ENTER YOUR PERSONAL INFORMATION***")
name = input("Enter your name : ")
age = int(input("Enter your age : "))
city = input("Enter your city : ")
college = input("Enter your college name : ")
percentage = float(input("Enter your percentage : "))
print()

print("***PERSONAL INFORMATION***")
print("NAME   :   ",name)
print("AGE    :   ",age)
print("CITY   :   ",city)
print("COLLEGE :  ",college)
print("PERCENTAGE : ",percentage)
