a = int(input("Enter the vlaue : "))
b = int(input("Enter the value : "))
print("a == b = ", a==b)
print("a != b = ", a!=b)
print("a > b = ", a>b)
print("a < b = ", a<b)
print("a >= b = ", a>=b)
print("a <= b = ", a<=b)
print("a >= b = ", a>=b)